### ISSUE TITLE
Simplify how images are built in this repo

### ISSUE THREAD

**Issue by jduimovich** [redhat-appstudio/build-definitions#13]
This repo creates multiple images for delivery into the app studio platform.
Default pipelines are delivered into `quay.io/redhat-appstudio/build-templates-bundle`
Base Image for the ClusterTasks are in `quay.io/redhat-appstudio/appstudio-utils`

The versions for these images are maintained separately in each directory which leads to confusion
Options
1. We change the release build to build both images at the same version. This requires the cluster tasks which are defined in the app studio environment to get version bumped every time any new release occurs. 
2. We write some update scripts which update the infra-deployment repository contents with the correct versions of the two (or more) images to prevent the wrong images updates.

I think we should do both -- and embed the automation in the .ci script for building and then installing new pipelines into app studio.

**Comment by jduimovich** [comment]
See https://github.com/redhat-appstudio/build-definitions/issues/13

**Comment by Michkov** [comment]
I have prepared a change which is integrated with git releases. It's extension of https://github.com/redhat-appstudio/infra-deployments/pull/56 . Basically when release in build-definitions is created, then it will trigger build of build-templates-bundle and appstudio-utils with tag of release tag. With this we can remove ClusterTasks from infra-deployments since we can point to kustomization.yaml in this repository and define which tag to use.

**Comment by Michkov** [comment]
Done in #19
